### ISSUE TITLE
Every URL resolves even if it's a 404

### ISSUE THREAD

**Issue by Gianlucamacis** [vijaycs85/sitemapextension#1]
Found an issue that all URLS "success" because a 404 page that has a design technically is still resolving. If you would like to repeat the situation that I came across:

1. Search for bbc.co.uk as an example
2. One of the results is a 404

**Comment by vijaycs85** [comment]
Fixed.

**Comment by vijaycs85** [comment]
![Result](https://cloud.githubusercontent.com/assets/1220029/26354883/7549ad0c-3fbe-11e7-9f62-e3e20cea33ec.png)
