### ISSUE TITLE
New command: check sitemap exists

### ISSUE THREAD

**Issue by Gianlucamacis** [vijaycs85/sitemapextension#2]
Provide a full list of all the sites you want to check in the CSV file but instead of chekcing all the sitemap URL's, it just checks if there are any URL's in the sitemap. If it finds at least 1 then it returns true and if it fails it returns false.

Ability to then export the results as a CSV :)

**Comment by vijaycs85** [comment]
Thanks @Gianlucamacis for raising this request. Looks like this could be another scenario to verify sitemap presence. Will look into this.

**Comment by vijaycs85** [comment]
>Provide a full list of all the sites you want to check in the CSV file

This is already available/possible. I need to document it.

> Ability to then export the results as a CSV :)

Moved this as separate request at #3. 

>instead of chekcing all the sitemap URL's, it just checks if there are any URL's in the sitemap. If it finds at least 1 then it returns true and if it fails it returns false.

I managed to check if the sitemap.xml is present or not.

![check for sitemap.xml](https://cloud.githubusercontent.com/assets/1220029/26355046/17d505a8-3fbf-11e7-9f28-7d7bc7c78d74.png)

**Comment by vijaycs85** [comment]
Fixed.
